from nltk import NaiveBayesClassifier as nbc
from nltk.tokenize import word_tokenize
from itertools import chain

training_data = [('6 more hours #HALO4','pos'),
('http:// Pornhub.com hits gone be low tonite #nerds #halo4 release 2nite','neg'),
('Since my #Halo4 is coming in the mail tomorrow, I'll be sending #Reach out in an appropriate form instead.','pos'),
('#halo4','pos'),
('Tomorrow is the biggest day in the history of this country. Please go out and get #Halo4','pos'),
('Over a hundred people at the @GAME_Canterbury Halo4 launch ...and a short dude as Master Chief as predicted. (not 9ft) http:// yfrog.com/gzdewqxoj','pos'),
('Bare long que at game so outside hmv hahaha #noque #halo4','pos'),
('#halo4 yes!!!!!!!!! pic.twitter.com/klVy6qg0','pos'),
('whos picking up #Halo4 tonight?','pos'),
('@JaaackPhelps too fucking right mate! #Halo4','pos'),
('The guns are great, they sound amazing. Map design is great and the graphics are amazing. #Halo4 is pretty good.','pos'),
('@Mike_Dege look whats trending bitch #Halo4','neg'),
('RT if your buying #halo4 !!','pos'),
('WHO'S READY FOR HALO 4!? #Halo4 pic.twitter.com/Ia0TPhCO','pos'),
('@BullyBrew Hopefully I'll be picking up Halo4 tomorrow, if so, I'll start with the campaign because I have never played the multiplayer lol','pos'),
('If i hadn’t played 3, Halo 4 just might’ve been the best game I’ve played. But I have played 3. #Halo4','pos'),
('#movember Day 5 #halo4 midnight launch. http:// instagr.am/p/Rqso5gKwG4/','pos'),
('#Halo4 >>>>>','pos'),
('#halo4','pos'),
('#yeahmygirlfriend #whatsamelbournecup ? #halo4 danna_mac http:// instagr.am/p/RqsoNJi9Pp/','pos'),
('R. I. P. to the competition #Halo4','pos'),
('Gotta fuel up before I return to the fight! #halo4 @Chipotle Mexican Grill http:// instagr.am/p/Rqsm8hqa4K/','neg'),
('The recruits are lined up and ready #HALO4 pic.twitter.com/09NRjORN','pos'),
('Nearly time... #halo4 pic.twitter.com/eCxgbcEl','pos'),
('...and tell me again...why r we counting down the hours until Halo4 hits the streets??','pos'),
('Finally! #halo4 http:// instagr.am/p/Rqsmn4PHhy/','pos'),
('@FurrrSure wanna coop #Halo4 campaign?','pos'),
('Noobs will be tebagged tonight! #halo4','pos'),
('Was great fun playin #Halo4 @4damelane tonight tunes were pumpin @stevencooperdj','pos'),
('Halo4 all night...','pos'),
('5 hours and 1 min tell #halo4 #nerdstatus','pos'),
('Tearing it up on reach, now time to rest up for #Halo4','pos'),
('Et voila, c'est le jour #Officiel de la sortie de #Halo4 ! Mon jeu préféré.Une grosse tuerie sa doit être (#Yoda#Powa). Oubliez pas ma chaine','pos'),
('Mr. Nice Guy @budnoob & Pad-Zerstörer @Bimon gab es gut gelaunt & ohne Star-Allüren. Ein kurzer Plausch war auch drin. Danke, Jungs! #Halo4','neg'),
('I CAN'T WAIT TO USE PROMETHEAN VISION. #halo4','pos'),
('@RhysGron91 cwtched up in bed warm #halo4 downstairs already','pos'),
('I'm gonna hit 25K tweets tonight when i get #Halo4 it is certain.','pos'),
('#Halo4 only 6 hours :D','pos'),
('5 hours. #Halo4','pos'),
('#EvilAwakens at Midnight!!! I'm Ready. #Halo4 #Hype','pos'),
('Midnight release of #Halo4 Male by chance, White by divine intervention, Gamer by choice.','pos'),
('THE CHIEF IS BACK BABY FUCK YEAH!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! #Halo4 #AncientEvilAwakens','neg'),
('Dame torrow halo4 cant wait !!','pos'),
('i got the #halo4 limited edition… i don't even know what it comes with, guess ill see tonight..','neg'),
('@Spawnnoyrenkjn ya il be doing full halo4 campaign play through & a BO2 Zombies campaign playthrough too :) as well as normal zombies & MP!!','pos'),
('F-Yea #Halo4','pos'),
('I hate to say it, but I'm not leaving my house for awhile after tonight #halo4','neg'),
('aaand #Halo4 is out aand im at home ..... -_-','pos'),
('I bet #Halo4 will suck.','neg'),
('Time for some Deus Ex: Human Revolution, then the newest episode of #RedvsBlue and finally #EvilAwakens #John -117 in #Halo4 !','pos'),
('@AOTS Master Chief lives in my room #aots #halo4 http:// via.me/-6okrswe','pos'),
('@GAMECannock RT @stevenLlewellyn : Even Spartans want to get hold of Halo4 pic.twitter.com/ZeB55omL','pos'),
('Glad for once I didn't need to queue for a big game and that I can sleep easy knowing my #Halo4 is already here','pos'),
('31 & 13... Feeed mee moreee!!! Ahhhh #Halo4 WHO GON STOP ME HUHHHHHH?! http:// instagr.am/p/RqsirOoGlA/','neg'),
('Wishing I had an XBOX...oh Chief how I miss you. #halo4','pos'),
('On a misson to carms to get Halo4 with@JDswarez #UNSC #excited','pos'),
('I'm queuing in fucking tescos for halo4 what is my life coming to...','pos'),
('#halo4','pos'),
('#Halo4 in 8 hrs!!','pos'),
('I finally watched Forward Unto Dawn. Wow...just, wow. #Halo4','pos'),
('I really cant wait till this game #halo4','pos'),
('Halo 4 Tourney info here! http:// theendgamesblog.com/?p=84 #Halo4 #Charlottesville','pos'),
('Kids in bed quick game of halo4 then I have to go to bed kids vs halo4 launch = kids win','pos'),
('Bought #Halo4 back in march, now I'm picking up @kpdoee to go grab it #stoked','pos'),
('Better wait 'til 12 to play Halo4 , 'advanced copies' = instant XBOXlive bans. Same for gamers being sexist online. ~SR pic.twitter.com/Xu9w9TMW','pos'),
('HALO FUCKING 4 IS OUT IN 1MIN #halo4 #forwarduntodawn #masterchief #343','pos'),
('HALO 4 HALO 4 HALO 4. #omg #Halo4','pos'),
('Outside game in southend waiting for halo4 !!! #bigmotherfuckingnerd !','pos'),
('#Halo4','pos'),
('#halo4','pos'),
('#Halo4 !!!!!?!!??!??!! @HaloWaypoint','pos'),
('I'm not homeless I'm waiting for halo4 #halo4 pic.twitter.com/mEupQJSQ','pos'),
('1 FUCKING MINUTE :D :D :D #Halo4 #AncientEvilAwakens','pos'),
('Stoked to get halo4 tonight.','pos'),
('Test, dinner, movie, Halo4 . #LFG','pos'),
('Even Spartans want to get hold of Halo4 pic.twitter.com/ZeB55omL','pos'),
('2 tvs 2 xboxs its about to go down! #halo4 #halo #xbox #xbox360 #gamerelease #videogames #multiplayer #insta http:// instagr.am/p/RqsTwVKyIb/','pos'),
('6 hours! #Halo4 #GamerTweet','pos'),
('#IFWEDATE I WANNA MARINATE AND BY MARINATE I MEAN WE YOU STROKIN MY TAIL WHILE IM WEARIN MY WILFRED COSTUME PLAYIN #HALO4','pos'),
('Menu song is soooo good. #Halo4','pos'),
('Eagerly awaiting #Halo4 ! Two minutes! pic.twitter.com/lNN5sQjq','pos'),
('Bring it #Halo4 pic.twitter.com/YA9dlWVB','pos'),
('Hitler is at the midnight #Halo4 Launch in Craigavon. So's Falloon and Jordy P!!','pos'),
('L'ami @JulienChieze aux commandes... #halo4 pic.twitter.com/pTsvsuz2','pos'),
('@VelVelHoller Got awesome reviews, not enough cash though coz i need to renew my xbox live too so it'd cost me £80 :( not fair. #Halo4','pos'),
('They're doing a raffle outside. Chance to win the Halo xbox, Samsung notebook and the game! #Halo4 #Halo4Stratford pic.twitter.com/3STi5oNV','pos'),
('Good report card promise to my little man = me standing outside #gamestop for 3 or so hours to pickup #halo4 #goodjoblittleguy #isitoveryet ?','pos'),
('The Chief just brushed past me. #Halo4 #Flailing','pos'),
('I can count the hours on one hand... #Pumped #Halo4','pos'),
('Waiting in line for #Halo4 ! @GAMELincolnArch pic.twitter.com/1f1Ydr8i','pos'),
('@bradykorte gear up for halo 4 so we can get the penis emblem clan back together #halo4','pos'),
"('@infamousRic : just about 7 hours until Halo 4. #HALO4 #CHIEF #ForgetBlckOps ""u are trippin its halo and black ops 2 togetha ma bbrothaa""','pos'),"
('Anyone that's looking to play #Halo4 hit me up GohanTheSaiyan ill be playing all night long! Lets go!','pos'),
('Evening Twitter'rs! I'm on the late - and it's all about to begin!! #reclaimersaga #halo4','pos'),
('I am now standing in line for #Halo4 . Can't wait to have it inky hands.','pos'),
('6pm Muh'fuckas already lined up #Halo4 #NerdLife #NoLife #MomImBusy http:// instagr.am/p/RqsI-_KURB/','pos'),
('In the queue for #Halo4 :D','pos'),
('midnight can't come any faster. #Halo4','pos'),
('#halo4 #game #hyped free hard case!!!! @Game http:// instagr.am/p/RqsXnQpjfI/','pos'),
('People are camping out at GameStop.... #halo4','pos'),
('Saw all of Halo4 :Forward Unto Dawn over the weekend.Someone please explain why we don't have a feature length Halo movie by now.','pos'),
('Gamestop in Frankfort is actually crowded #halo4','pos'),
('The pieces are all coming together #Halo4 http:// instagr.am/p/Rqr4rFRKLI/','pos'),
('My cousin told me to go too the midnight release of Halo 4 , he said there is going to be bitches .... Lololol #NoBitchesAtGameStop #Halo4','neg'),
('Should I get #halo4 tonight or not? Ahhh 1st world problems.','neg'),
('Getting ready for Halo4 launch at The Domain Microsoft retail store in Austin. Come on by and see teh haloz!','pos'),
('6 more hours chief!! I hope your 5 year sleep has been peaceful. #halo4 #nonoobsplease','pos'),
('So... #Halo4 is the best shooter I've ever played','pos'),
"('“ @OJTheThing : Kanye West says no one man should have all that power"" but someone already does, his names Master Chief #Halo4 ” Preach""','neg'),"
('Decked out in my #UNSC gear for the #Halo4 midnight release. #stoked http:// instagr.am/p/RqsSQsFdTz/','pos'),
('Guys let's all be serious, the most important thing happening tomorrow is #Halo4','pos'),
('Playing some #TF2 with @360GhostSlayer to keep my mind off of #Halo4','pos'),
('Sweet! 8th in line for Halo 4!!! Can't wait to see the crowd later haha #halo4 #allnighter','pos'),
('Bout to get my halo on tonight. #Halo4 #midnightevent #dontjudge','pos'),
('Funny that people still haven't got #Halo4 yet. Being playing it all evening. #SlowPokeGamers','pos'),
('2 Mins :D #Halo4 #AncientEvilAwakens','pos'),
('MIDNIGHT #Halo4','pos'),
('Stc, y u no midnight release Halo4 :(','neg'),
('Tomorrow is going to be a good day :) #3year #halo4 (in that order)','pos'),
('I got gas money n I'll smoke u out #Halo4','pos'),
('I think I'm losing my girlfriend for the next few days. Now taking Applications for a temporary replacement. #Halo4 @IzPandaface','neg'),
('Cannot get drunk. I am buzzed but I cannot get drunk. I have prior engagements to attend to. #Halo4','neg'),
('In the queue @gamedigital #halo4 http:// sdrv.ms/SQWrrb','pos'),
('@Tomiiks @JulienChieze @cyriloo yeahhhhh #halo4','pos'),
('Only one more day until #Halo4 will be in my possession!','pos'),
('@cliveXsXscout @Nak3dHalo Yeah, I wasn't certain if #Halo4 would be worth the shot','pos'),
('@HysteriaVG let me know if halo4 is worth buying..if it plays like call of duty i dont want it','pos'),
('How's #Halo4 not trending when its 4minutes from release?!? This is madness','neg'),
('Waiting in line for the midnight launch of Halo 4...not something you do everyday #halo4','pos'),
('I have a good feeling Obama will win this election. #Halo4','pos'),
('DAT AWKWARD MOMENT WHEN YOU PLAYIN DA HALO WHEN YOU IZ DA HALO #HALO4','neg'),
('The setup #Halo4 #Halo4Stratford pic.twitter.com/cQXtXbMR','pos'),
('5 hours #halo4','pos'),
('Who else is getting #Halo4 tonight? Gt:MissStateDawg','pos'),
('@iyiTweets sounds like a plan man #halo4','pos'),
('#haloman #Halo4 @gamepoole pic.twitter.com/y1VEnVwO','pos'),
('@HaloWaypoint @bsangel @AceyBongos @majornelson Not long now, love Swindon, UK: http:// yfrog.com/h88vpsuj #Halo4','pos'),
('Five minutes everyone. #Halo4 #EvilAwakens .','pos'),
('@Stereoscopic_3D ho il pad di #Halo4 della 360 :D','pos'),
('Anybody wanna goto gamestop with me at 830? #Halo4','pos'),
('Long wait #Halo4 @_Selw00d @_Jeaton @jackbell_94 @robbieonslow aha','pos'),
('#Halo4','pos'),
('RT if you are getting that Halo4 all up in your life tonight!','pos'),
('“@EthanReis: People already camping out for #Halo4 at Best Buy... That's crazy. #butilikeit #cantwait ” devotion at its finest !','pos'),
('Tomorrow really is a big day #Halo4 and #ElectionDay','pos'),
('@therealjbry example: cod is halo for black kids. (flashy, not fast paced, and trashy) halo4 is halo2 for black kids (list same reasons)','pos'),
('I hope everyone has fun voting tomorrow. I personally think we're screwed either way so I vote Master Chief. Halo 4 all day tomorrow. #Halo4','pos'),
('Just bought 3 2liter bottles of Dew. 2 regular bottles for myself. And doritos. #ready for the #halo4 release','pos'),
('Being a fanboy and getting halo at midnight, stocked up on curlywurlys for the long night ahead #HALO4','pos'),
('@Gamestratford #Halo4 launch is awesome! Free pizza! Great swag! Just awsome!!! #MidnightLaunch','pos'),
('#Halo4 Ya a salido oficialmente xDD ánimo @xDemen ya queda menos para el jueves jaja','pos'),
('#Halo4 comes out tonight... Looks like I better get some Xbox Live Gold! That is, unless someone is willing to give me some free time... Eh?','pos'),
('Apparently Sexism in #Halo4 earns you a lifetime ban','neg'),
"('#Halo4 will be mine in less than 1 day... ;)','pos'),"
('You will be mines tonight!! Can't wait #halo4 #halo #games #swag http:// instagr.am/p/RqsPR_SJkj/','pos'),
('3 Mins :D #Halo4 #AncientEvilAwakens','pos'),
('Saddest thing we've ever done @Plowman9 #halo4','neg'),
('@JakeMiller615 baby bro is ready for #Halo4 are you? pic.twitter.com/VX2RWg3f','pos'),
('gonna go get #Halo4 tonight!','pos'),
('Work Midnight release, get home play Halo until 6am, 4hour power nap, back into Halo. #Halo4','pos'),
('I know what I should be eating & drinking w/ #Halo4 but have any of the Presidential candidates indicated what my election snacks should be?','pos'),
('I wonder how many people are at @gamestop right now? #halo4','pos'),
('VG NEWS: 5 Hours Left Until The Release Of Halo 4 On Tuesday Nov 6th! http:// halo.xbox.com/halo4 #Halo4 #343Industries #news','pos'),
('Halo 4 midnight launch tonight! #Halo4','pos'),
('5 freakin' minutes! #Halo4','pos'),
('Masterchief for president #Halo4','pos'),
('5 minutes!! #halo4','pos'),
('1st in queue #halo4 . @tomojackson14 @GrantBenham0995','pos'),
('I just might have to get #halo4','pos'),
('#Halo4 tomorrow!','pos'),
('Cunt stole first place from me… #halo4','neg'),
('FIVE MINUTES! #Halo4','pos'),
('@G_Wizzle_94 @filmcafe_steve the world is going to go into meltdown in 5 min #halo4','pos'),
('I think I will be the only person not playing #halo4 tonight http:// instagr.am/p/RqsJ4du5lf/','neg'),
('SIX MINUTES! #Halo4','pos'),
('SEVEN MINUTES! #Halo4','pos'),
('EIGHT MINUTES! #Halo4','pos'),
('NINE MINUTES! #Halo4','pos'),
('@AOTS Dilemma! Vote or Pwn peeps on Halo 4. Now thats a decision! #Halo4 #ElectionDay #AOTS','neg'),
('@BrandonFasulka haha hell yes!:) #halo4','neg'),
('I've never been so excited for a game yet I can't get it #Halo4 #BrokeLife','pos'),
('Midnight release almost on us #Halo4 :D @GAMENewcastle pic.twitter.com/p1RtOZGG','pos'),
('I'm voting tomorrow, but since I dislike both candidates,I'm penciling in a new one. #MasterChief #Halo4 @HaloWaypoint pic.twitter.com/7NGlaVqo','neg'),
('@burrrady tomorrow can't get any better #kidinksingle #halo4','neg'),
('Hope everyone gets their copy of Halo after queuing for it. I shall join the Halo crew once i have time & the mad review season is up #Halo4','pos'),
('@BarackObama wants me to play #Halo4 tomorrow? Yes sir, Mr. President.','pos'),
('is pumped for #Halo4 but I can't pick it up till tomorrow night, damn work lol #KCCO','pos'),
('#Halo4 Wake up John','pos'),
('1st in line for #Halo4','pos'),
"('Kanye West says no one man should have all that power"" but someone already does, his names Master Chief #Halo4""','neg'),"
('@aethyal @NextGenTactics Machinima can claim Halo4 . Well, at least that's what I've been told.','pos'),
('Excited for #halo4 2moro! Woooo!','pos'),
('Walked past a game store on the way to work to see people queuing for #Halo4 and playing the multiplayer! It's not fair I want to play!','pos'),
('@leondoell #nerdnews about #Halo4 way better!!!! :D @HaloWaypoint','pos'),
('And now the wait begins. #halo4','pos'),
('#Halo4 thanks to my mam I can't get Xbox live :( I WANNA PLAY HALO','pos'),
('Stood in gamestation #nerd #halo4','pos'),
('Great to work at the Xbox Halo 4 launch! Great turn out and venue looked fantastic! Fab job done by all involved! #halo4 #xbox #dublin','pos'),
('The great debate: Get #Halo4 tonight, or wait until tomorrow?','pos'),
('I'm literally on the road to #Halo4 . 250km out.','pos'),
('Halo4 Tonight. It's Real.','pos'),
('And hour and a half at the front of the queue to be pushed away by people who run to a shop door? Idiots. #Halo4','pos'),
('Hm ich weiß nicht ob ich mir noch Halo4 besorgen soll','pos'),
('#Halo4 tonight not going to sleep','pos'),
('#lessgo #Halo4','pos'),
('I wanna get #Halo4 already. This is gonna be a long day.','pos'),
('According to the Xbox dashboard, there is only 5 minutes until the UK launch of #Halo4','pos'),
('#MasterChief4Prez #Halo4','pos'),
('5 minutes till #Halo4','pos'),
('D'autres suivront les élections US moi je serai sur #Halo4','pos'),
('#Halo4 I can almost feel it.','pos'),
('@_MyNamesBen oi fort u woulf be getting halo4 ?','pos'),
('#Halo4 at #GAME hyped!','pos'),
('Someone buy me #Halo4 .. pleaaase & thank youu !','pos'),
('sat staring at my tv waiting for @cwurtles to return from asda with his #Halo4 despite the fact he pre-ordered it off amazon..','pos'),
('Welcome aboard the UNSC INFINTY. #halo4 #gamernation #mosaicxm @The UNSC INFINITY- Halo 4 Launch http:// instagr.am/p/RqsDR7FJgN/','pos'),
('Halo4 midnight release >> work','pos'),
('#HALO4 RT if ur Hyped!!','pos'),
('Still feeling well and halo4 comes 2moro so at least ill have something to do when I'm chemoed','neg'),
('yup, I'm excited :) #halo4 http:// instagr.am/p/RqsFZCzLVu/','pos'),
('On my way to buy #Halo4','pos'),
('They are already selling #Halo4 at the Microsoft Company Store. Rumor says the line goes all around the building. I'm here stuck at work.','neg'),
('These next 5 hours need to speed the fuck up... #Halo4','neg'),
('Hurry Up #Halo4 ! :D','pos'),
('Midnight come sooner #halo4','pos'),
('#Halo4 6 hous 17 mins WoW http:// usmc54.wix.com/halofansforlif e#!home/mainPage …','pos'),
('@mkthorn I would but.................................. HALO4 #imgay #judge #idgaf','pos'),
('@bungie @halowaypoint hopefully one of many #clutch moments I will have for #Halo4 !! pic.twitter.com/u8U3vSpe','pos'),
('Midnight release tonight, gonna be a long night! #Halo4','pos'),
('Awkwardly waiting alone in Tescos for #Halo4','neg'),
('I am so Nostalgic right now. Just looking back at all the Halo games and it is such an awesome series! #Halo4','pos'),
('@DAaron890 you have halo4 and your playing combat evolved','neg'),
('east coast, t-minus 5 hours! #Halo4','pos'),
"('All of you in England are so lucky ;) #Halo4','pos'),"
('#HALO4 WE IN DAT ASS ITS ALMOST TIME FO DA REZZURECTION OF 2PAC IN HIS NEW FORM HALO4PAC!!!!!!!!!','neg'),
('#Halo4 tomorrow.','pos'),
('Does my face look halo in this?? #topdogpaintball down for the #halo4 launch at @GAMEGreatMouth pic.twitter.com/vVcskVpj','pos'),
('I really want the Halo 4 edition xbox. #Halo4editionxbox #Halo4 http:// instagr.am/p/Rqr5_5Bt8c/','pos'),
('5 hours, 6 minutes and 15 seconds to go! #Halo4','pos'),
('7 fucking hours #Halo4 bitches','neg'),
('Mañana empieza la viciada total, estaré off supongo XD #Halo4 http://www. youtube.com/watch?feature= player_embedded&v=NEEOdyqhziA#… !','pos'),
('5 Mins :D #Halo4 #AncientEvilAwakens','pos'),
('AAAGGGGGHHHHHHHHH #Halo4','pos'),
('Picking up #HALO4 tomorrow, and #BlackOpsII next week','pos'),
('@DFWTicketHunter See you online tonight around 12:15? #halo4','pos'),
('Tonight is the #HALO4 launch in our stores. Lot of work to be done. I think I would rather be doing demo for it then take calls. #JustSaying','pos'),
('FUUUUUUUUUUUUUUUUU! NVRMIND FIRST 100! #HALO4 http:// instagr.am/p/Rqr4g6Qq2T/','pos'),
('5 hours 7 minutes... #Halo4','pos'),
('@ChrisGonzalez57 fml...tomorrow is the day that i lose you :/ #Halo4 #FriendshipLost :(','neg'),
('Almost Game-Time!!!! #Halo4 !!!!! http:// instagr.am/p/RqsBRMQxAy/','pos'),
('#halo4 tomrorrow! Only #Microsoft product I like','pos'),
('@WORICP halo4 ? :P','pos'),
('bonne lecture technologique #HALO4 Techno | Actualité | Le Journal de Québec http://www. journaldequebec.com/2012/10/31/lyt ro-revolution-photo …','pos'),
('Ready for midnight... #halo4 pic.twitter.com/n9EoOSrQ','pos'),
('I am so pumped to be anti social :) #halo4','pos'),
('Are you prepared #Halo4 pic.twitter.com/3ezOZ5y6','pos'),
('Gonna be a cold midnight release tonight. #halo4','pos'),
('5 hours 7 minutes #Halo4','pos'),

]

vocabulary = set(chain(*[word_tokenize(i[0].lower()) for i in training_data]))

feature_set = [({i:(i in word_tokenize(sentence.lower())) for i in vocabulary},tag) for sentence, tag in training_data]

classifier = nbc.train(feature_set)

test_sentence = "This looks so bad this game does"
featurized_test_sentence =  {i:(i in word_tokenize(test_sentence.lower())) for i in vocabulary}

print "test_sent:",test_sentence
print "tag:",classifier.classify(featurized_test_sentence)